version: '3.8'

services:
  nginx:
    image: nginx:1.20.1
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - "todo-frontend-prod"
      - "todo-backend-prod"
    ports:
      - 8080:80
    container_name: todo-reverse-proxy
  todo-frontend:
    image: todo-frontend-prod
    build:
      context: ./todo-frontend/
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URL=api/
    container_name: todo-frontend-prod
  todo-backend:
    image: todo-backend-prod
    build:
      context: ./todo-backend/
      dockerfile: Dockerfile
    depends_on:
      - "todo-mongo-prod"
      - "todo-redis-prod"
    container_name: todo-backend-prod
    environment:
      - REDIS_URL=redis://todo-redis-prod:6379
      - MONGO_URL=mongodb://the_username:the_password@todo-mongo-prod:27017/the_database
  mongo:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    container_name: todo-mongo-prod
    volumes: 
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db
  redis:
    image: redis
    command: ['redis-server', '--appendonly', 'yes']
    container_name: todo-redis-prod
    volumes: 
      - ./todo-backend/redis_data:/data