version: '3.8'

services:
  todo-frontend:
    image: todo-frontend-dev
    build:
      context: ./todo-frontend/
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-frontend/:/usr/src/app
    container_name: todo-frontend-dev
    ports: 
     - 3000:3000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3001
      - CHOKIDAR_USEPOLLING=true
  todo-backend:
    image: todo-backend-dev
    build:
      context: ./todo-backend/
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-backend:/usr/src/app
    ports: 
     - 3001:3001
    depends_on:
      - "todo-mongo-dev"
      - "todo-redis-dev"
    container_name: todo-backend-dev
    environment:
      - PORT=3001
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - CHOKIDAR_USEPOLLING=true
  mongo:
    image: mongo:4.4
    ports:
     - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    container_name: todo-mongo-dev
    volumes: 
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db
  redis:
    image: redis
    ports:
     - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']
    container_name: todo-redis-dev
    volumes: 
      - ./todo-backend/redis_data:/data