version: '3.8'

services:
  blog-frontend-dev:
    image: blog-frontend-dev
    build:
      context: ./blog-frontend/
      dockerfile: dev.Dockerfile
      args:
       - REACT_APP_BACKEND_URL=http://localhost:3003
    volumes:
      - ./blog-frontend/:/usr/src/app
    container_name: blog-frontend-dev
    ports:
     - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  blog-backend-dev:
    image: blog-backend-dev
    build:
      context: ./blog-backend/
      dockerfile: dev.Dockerfile
    volumes:
      - ./blog-backend/:/usr/src/app
    container_name: blog-backend-dev
    ports:
      - 3003:3003
    environment:
      - CHOKIDAR_USEPOLLING=true
      - SECRET=asd 
      - PORT=3003 
      - SKIP_PREFLIGHT_CHECK=true 
      - MONGODB_URI=mongodb://the_username:the_password@blog-mongo:27017/the_database
  mongo:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    container_name: blog-mongo
    volumes: 
      - ./blog-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./blog-backend/mongo_data:/data/db